- name: change Auth method
  replace:
    dest=/etc/postgresql/9.3/main/pg_hba.conf
    regexp='^(local\s+all\s+all\s+)peer'
    replace='\1md5'
    backup=yes
    owner=postgres
    group=postgres
    mode=0640
  register: pg_update_auth_method

- name: postgresql restart
  service:
    name=postgresql
    state=reloaded
  when: pg_update_auth_method.changed

- include: init_db/postgresqal.yml
