#! vi: set filetype=ansible:
---
- include: package/main.yml

- include: zabbix_server.yml
  when: monitoring_master

- include: ./config/main.yml
  when: monitoring_master

- include: zabbix_agent.yml
