- name: add zabbix officical repository key
  apt_key:
    url=http://repo.zabbix.com/zabbix-official-repo.key
    state=present
- name: add zabbix officical repository
  apt_repository:
    repo={{ item }}
    state=present 
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'
    - 'deb-src http://repo.zabbix.com/zabbix/3.0/ubuntu trusty main'

- name: install zabbix server packages
  when: monitoring_master
  apt:
    name={{ item }}
    state=present
  with_items:
    - 'nginx'
    - 'php5-fpm'
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'zabbix-get'
    - 'python-psycopg2'
    - 'php5-pgsql'
    - 'fonts-ipaexfont'

- name: install zabbix agent
  apt:
    name=zabbix-agent
    state=present
