- apt_key:
    url=http://repo.zabbix.com/zabbix-official-repo.key
    state=present

- name: add zabbix officical repository (version 2.4, for ubuntu12.04)
  when: ansible_distribution_version == '12.04'
  apt_repository:
    repo={{ item }}
    state=present
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/2.4/ubuntu {{ ansible_distribution_release }} main'
    - 'deb-src http://repo.zabbix.com/zabbix/2.4/ubuntu {{ ansible_distribution_release }} main'

- name: add zabbix officical repository (version 3.0, for ubuntu14.04)
  when: ansible_distribution_version == '14.04'
  apt_repository:
    repo={{ item }}
    state=present
  with_items:
    - 'deb http://repo.zabbix.com/zabbix/3.0/ubuntu {{ ansible_distribution_release }} main'
    - 'deb-src http://repo.zabbix.com/zabbix/3.0/ubuntu {{ ansible_distribution_release }} main'
