- postgresql_user:
    name=zabbix
    password=6117982f58a0b71e
  become: yes
  become_user: postgres

- postgresql_db:
    name=zabbix owner=zabbix state=present
  become: yes
  become_user: postgres

- stat:
    path=/etc/zabbix/.create.sql.done
  register: create_db_sym

- shell: |
    gunzip -c /usr/share/doc/zabbix-server-pgsql/create.sql.gz | psql -U zabbix zabbix
  register: db_initialized_check
  environment:
    PGPASSWORD: 6117982f58a0b71e
  become: yes
  become_user: postgres
  when: create_db_sym.stat.exists == False

- file:
    path=/etc/zabbix/.create.sql.done
    state=touch
    owner=root
    group=root
    mode=644
  when: db_initialized_check.changed
