- name: install zabbix server packages
  when: monitoring_master
  apt:
    name={{ item }}
    state=present
  with_items:
    - 'nginx'
    - 'php5-fpm'
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'zabbix-get'
    - 'python-psycopg2'
    - 'php5-pgsql'
    - 'fonts-ipaexfont'
