- template:
    src={{ item }} 
    dest=/{{ item|regex_replace('\.j2$', '') }}
    owner=root
    group=root
    mode=0644
  with_items:
    - 'etc/php5/fpm/php-fpm.conf.j2'
    - 'etc/php5/fpm/php.ini.j2'
    - 'etc/php5/fpm/pool.d/www.conf.j2'
  notify:
    - php5-fpm restart

- template:
    src={{ item }}
    dest=/{{ item|regex_replace('\.j2$', '') }}
    owner=root
    group=root
    mode=0644
  with_items:
    - 'etc/nginx/sites-available/zabbix_frontend.j2'
    - 'etc/nginx/conf.d/logformat.conf.j2'
  notify:
    - nginx reload

- file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - nginx reload

- file:
    src=../sites-available/zabbix_frontend
    dest=/etc/nginx/sites-enabled/zabbix_frontend
    state=link
  notify:
    - nginx reload
