- name: add zabbix officical repository key
  include: package/repository.yml
  when:
    ansible_distribution == 'Ubuntu'
    and
    ansible_distribution_version == '14.04'

- name: install zabbix server packages
  when: monitoring_master
  apt:
    name={{ item }}
    state=present
  with_items:
    - 'nginx'
    - 'php5-fpm'
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'zabbix-get'
    - 'python-psycopg2'
    - 'php5-pgsql'
    - 'fonts-ipaexfont'

- name: install zabbix agent
  apt:
    name=zabbix-agent
    state=present
